# HubPvP by Quared, v${project.version}
# Have an issue? Report it on our Spigot page!



# --------------------------------------------------
# General
# --------------------------------------------------

# Change the cooldown when enabling/disabling PvP (seconds). Set to 0 to disable.
enable-cooldown: 3
disable-cooldown: 0

# Respawn location
respawn:
  enabled: true # Should HubPvP teleport a player when they die?
  use-world-spawn: false # Overrides x, y, z, yaw, pitch
  x: 0
  y: 100
  z: 0
  yaw: 0
  pitch: 0

# How much health is regained on kill, this is in HP, not hearts. Set to -1 to disable
health-on-kill: 4
health-gained-message: '&aYou killed %killed% and gained +%extra% health!'

disabled-worlds:
  - world_nopvp

# --------------------------------------------------
# Messages
# --------------------------------------------------

lang:
  pvp-enabled: '&e> &7Your &cPvP Mode &7has been &aactivated&7!'
  pvp-enabling: '&7Your &cPvP Mode &7will activate in &e%time%'
  pvp-disabled: '&e> &7Your &cPvP Mode &7has been &cdeactivated&7!'
  pvp-disabling: '&cPvP disabling in %time% second(s).'
  reloaded: '&aSuccessfully reloaded the HubPvP config!'
  killed: '&4%killer% &chas killed you.'
  killed-other: '&eYou have killed &6%killed%&e!'
  disabled-in-world: "&cYou may not use this in this world!"

# --------------------------------------------------
# Item Customisation
# --------------------------------------------------

items:
  weapon:
    slot: 9 # Sword slot inside the player's inventory
    material: DIAMOND_SWORD # Item to use as the sword
    name: '&7> &#9e00ff&lP&#9321ff&lv&#8843ff&lP &#7d64ff&lS&#7286ff&lw&#67a7ff&lo&#5cc9ff&lr&#51eaff&ld &7<' # Name of the item
    lore: # Item description, shown when hovering over in inventory
      - "&9&l| HOW IT WORKS?"
      - "&9&l|"
      - "&9&l| &fEquipping this sword engages &9PvP &fand &9armor&f."
      - "&9&l| &aSafe in spawn&f: lose hearts, not stuff."
      - "&9&l| &cRisky in warzone/wild&f: lose everything,"
      - "&9&l| &fincluding sword. Be careful."
    enchantments:
      - "sharpness:1"
    custom_model_data: 484985
  helmet:
    material: DIAMOND_HELMET # Item to use as the helmet
    enchantments:
      - "protection:1"
    custom_model_data: 484986
  chestplate:
    material: DIAMOND_CHESTPLATE # Item to use as the chestplate
    custom_model_data: 484987
  leggings:
    material: DIAMOND_LEGGINGS # Item to use as the leggings
    custom_model_data: 484988
  boots:
    material: DIAMOND_BOOTS # Item to use as the boots
    custom_model_data: 484989