# HubPvP by Quared, v${project.version}
# Have an issue? Report it on our Spigot page!



# --------------------------------------------------
# General
# --------------------------------------------------

# Change the cooldown when enabling/disabling PvP (seconds). Set to 0 to disable.
enable-cooldown: 3
disable-cooldown: 0

# Respawn location
respawn:
  enabled: true # Should HubPvP teleport a player when they die?
  use-world-spawn: false # Overrides x, y, z, yaw, pitch
  x: 0
  y: 100
  z: 0
  yaw: 0
  pitch: 0

# How much health is regained on kill, this is in HP, not hearts. Set to -1 to disable
health-on-kill: 4
health-gained-message: '&aYou killed %killed% and gained +%extra% health!'

disabled-worlds:
  - world_nopvp

# --------------------------------------------------
# Messages
# --------------------------------------------------

lang:
  pvp-enabled: '&6&l>&r&a PvP enabled!'
  pvp-enabling: '&aPvP enabling in %time% second(s).'
  pvp-disabled: '&6&l>&r&c PvP disabled!'
  pvp-disabling: '&cPvP disabling in %time% second(s).'
  reloaded: '&aSuccessfully reloaded the HubPvP config!'
  killed: '&4%killer% &chas killed you.'
  killed-other: '&eYou have killed &6%killed%&e!'
  disabled-in-world: "&cYou may not use this in this world!"

# --------------------------------------------------
# Item Customisation
# --------------------------------------------------

items:
  weapon:
    slot: 9 # Sword slot inside the player's inventory
    material: DIAMOND_SWORD # Item to use as the sword
    name: '&7> &#db86e6&lP&#da85d0&lv&#d984ba&lP &#d883a4&lS&#d8818d&lw&#d78077&lo&#d67f61&lr&#d57e4b&ld &7<' # Name of the item
    lore: # Item description, shown when hovering over in inventory
      - "&7Equip this sword to fight other players!"
    enchantments:
      - "sharpness:1"
  helmet:
    material: DIAMOND_HELMET # Item to use as the helmet
    enchantments:
      - "protection:1"
  chestplate:
    material: DIAMOND_CHESTPLATE # Item to use as the chestplate
  leggings:
    material: DIAMOND_LEGGINGS # Item to use as the leggings
  boots:
    material: DIAMOND_BOOTS # Item to use as the boots